name: End-to-End test
on: push
jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Execute the test scripts
              uses: cypress-io/github-action@v6
            

